# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semiRestUsers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='users',
            name='lastName',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
